ERROR - 2023-01-13 06:35:14 --> Error connecting to the database: ErrorException: pg_pconnect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:69
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_pconnect(): ...', 'C:\\xampp\\htdocs...', 69)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(69): pg_pconnect('host=localhost ...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(382): CodeIgniter\Database\Postgre\Connection->connect(true)
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(31): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->index()
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-01-13 06:35:14 --> Unable to connect to the database.
Main connection [Postgre]: pg_pconnect(): Unable to connect to PostgreSQL server: fe_sendauth: no password supplied
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "proveedor"
ORDER BY "id" ASC', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ISPController.php(31): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->index()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 06:48:19 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=13420 in C:\xampp\htdocs\caidas-internet\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 171)
#1 C:\xampp\htdocs\caidas-internet\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('p:localhost', 'root', '', 'control_ISP', 5432, '', 0)
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(true)
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(31): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->index()
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\caidas-internet\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\caidas-internet\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('p:localhost', 'root', '', 'control_ISP', 5432, '', 0)
#1 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(true)
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\caidas-internet\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(31): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->index()
#8 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\caidas-internet\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(true)
#1 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\caidas-internet\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(31): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->index()
#7 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#8 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-01-13 06:48:19 --> Unable to connect to the database.
Main connection [Mysqli]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `proveedor`
ORDER BY `id` ASC', [], false)
 3 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(586): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ISPController.php(31): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->index()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:08:16 --> Undefined array key "verificar"
in APPPATH\Controllers\ISPController.php on line 48.
 1 APPPATH\Controllers\ISPController.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "verificar"', 'APPPATH\\Controllers\\ISPController.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
 3 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 4 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:08:46 --> Undefined array key "verificar"
in APPPATH\Controllers\ISPController.php on line 48.
 1 APPPATH\Controllers\ISPController.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "verificar"', 'APPPATH\\Controllers\\ISPController.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
 3 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 4 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:08:59 --> Undefined array key "verificar"
in APPPATH\Controllers\ISPController.php on line 48.
 1 APPPATH\Controllers\ISPController.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "verificar"', 'APPPATH\\Controllers\\ISPController.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
 3 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 4 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:15:45 --> Undefined variable $incorrecto
in APPPATH\Views\control_internet.php on line 19.
 1 APPPATH\Views\control_internet.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $incorrecto', 'APPPATH\\Views\\control_internet.php', 19)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\control_internet.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1135): CodeIgniter\View\View->render('control_internet', [], true)
 5 APPPATH\Controllers\ISPController.php(36): view('control_internet', [...])
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->index()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:19:14 --> Undefined variable $incorrecto
in APPPATH\Views\control_internet.php on line 19.
 1 APPPATH\Views\control_internet.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $incorrecto', 'APPPATH\\Views\\control_internet.php', 19)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\control_internet.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1135): CodeIgniter\View\View->render('control_internet', [], true)
 5 APPPATH\Controllers\ISPController.php(36): view('control_internet', [...])
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->index()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:28:44 --> Undefined global variable $_SESSION
in APPPATH\Views\control_internet.php on line 19.
 1 APPPATH\Views\control_internet.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined global variable $_SESSION', 'APPPATH\\Views\\control_internet.php', 19)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\control_internet.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1135): CodeIgniter\View\View->render('control_internet', [], true)
 5 APPPATH\Controllers\ISPController.php(36): view('control_internet', [...])
 6 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->index()
 7 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 8 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 09:34:21 --> The route for "control_internet" cannot be found.
in SYSTEMPATH\HTTP\RedirectResponse.php on line 60.
 1 SYSTEMPATH\HTTP\RedirectResponse.php(60): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('control_internet')
 2 SYSTEMPATH\Common.php(861): CodeIgniter\HTTP\RedirectResponse->route(false)
 3 APPPATH\Controllers\ISPController.php(63): redirect('control_internet')
 4 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
 5 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 6 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:13:01 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «observacion» en la relación «data_control»
LINE 1: ... &quot;proveedor_id&quot;, &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observaci...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:13:01 --> pg_query(): Query failed: ERROR:  no existe la columna «observacion» en la relación «data_control»
LINE 1: ... &quot;proveedor_id&quot;, &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observaci...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la columna «observacion» en la relación «data_control»
LINE 1: ... &quot;proveedor_id&quot;, &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observaci...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:15:23 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «observacion» en la relación «data_control»
LINE 1: ... &quot;proveedor_id&quot;, &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observaci...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:15:23 --> pg_query(): Query failed: ERROR:  no existe la columna «observacion» en la relación «data_control»
LINE 1: ... &quot;proveedor_id&quot;, &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observaci...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la columna «observacion» en la relación «data_control»
LINE 1: ... &quot;proveedor_id&quot;, &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observaci...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:17:54 --> ErrorException: pg_query(): Query failed: ERROR:  no existe la columna «tiempo_control» en la relación «data_control»
LINE 1: ..., &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observacion&quot;, &quot;tiempo_co...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:17:54 --> pg_query(): Query failed: ERROR:  no existe la columna «tiempo_control» en la relación «data_control»
LINE 1: ..., &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observacion&quot;, &quot;tiempo_co...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  no existe la columna «tiempo_control» en la relación «data_control»
LINE 1: ..., &quot;fecha_corte&quot;, &quot;fecha_resuelto&quot;, &quot;observacion&quot;, &quot;tiempo_co...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:27:18 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time with time zone: «8 dia / 0 mes / 00 año,  00h-0min-0s»
LINE 1: ...3-01-10T14:05', '2023-01-18T14:05', 'Obervacion', '8 dia / 0...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:27:18 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time with time zone: «8 dia / 0 mes / 00 año,  00h-0min-0s»
LINE 1: ...3-01-10T14:05', '2023-01-18T14:05', 'Obervacion', '8 dia / 0...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time with time zone: «8 dia / 0 mes / 00 año,  00h-0min-0s»
LINE 1: ...3-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:31:49 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('1', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:31:49 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('1', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'1\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:32:25 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('1', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:32:25 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('1', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'1\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'1\', \'1\', \'2023-01-10T14:05\', \'2023-01-18T14:05\', \'Obervacion\', \'8 dia / 0 mes / 00 año,  00h-0min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:33:54 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:33:54 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'2\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:34:09 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:34:09 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'2\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:34:27 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:34:27 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'2\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:36:02 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:36:02 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'2\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:39:33 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:39:33 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'2\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-13 11:40:05 --> ErrorException: pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^ in C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php:140
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\caidas-internet\system\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\caidas-internet\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\caidas-internet\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\caidas-internet\system\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\caidas-internet\system\BaseModel.php(750): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\caidas-internet\system\Model.php(695): CodeIgniter\BaseModel->insert(Array, true)
#8 C:\xampp\htdocs\caidas-internet\app\Controllers\ISPController.php(57): CodeIgniter\Model->insert(Array)
#9 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
#10 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
#11 C:\xampp\htdocs\caidas-internet\system\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\caidas-internet\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-01-13 11:40:05 --> pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES ('2', '1', '2023-01-1...
                                                             ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 140.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  la sintaxis de entrada no es válida para tipo time: «2023-01-10T14:05»
LINE 1: ...observacion&quot;, &quot;tiempo_control&quot;) VALUES (\'2\', \'1\', \'2023-01-1...
                                                             ^', 'SYSTEMPATH\\Database\\Postgre\\Connection.php', 140)
 2 SYSTEMPATH\Database\Postgre\Connection.php(140): pg_query(Object(PgSql\Connection), 'INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 3 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 4 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (\'2\', \'1\', \'2023-01-10T14:05\', \'2023-01-11T04:15\', \'prueba\', \'0 dia / 0 mes / 00 año,  14h-10min-0s\')')
 5 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO "data_control" ("sucursal_id", "proveedor_id", "fecha_corte", "fecha_resuelto", "observacion", "tiempo_control") VALUES (:sucursal_id:, :proveedor_id:, :fecha_corte:, :fecha_resuelto:, :observacion:, :tiempo_control:)', [...], false)
 6 SYSTEMPATH\Model.php(303): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(695): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\ISPController.php(57): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->agregar()
11 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
12 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 12:26:36 --> Class "App\Models\Proveedor" not found
in APPPATH\Controllers\ISPController.php on line 19.
 1 APPPATH\Controllers\ISPController.php(32): App\Controllers\ISPController->instaciaProvee()
 2 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISPController->index()
 3 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISPController))
 4 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 12:39:17 --> Invalid file: control_internet.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('control_internet.php')
 2 SYSTEMPATH\Common.php(1135): CodeIgniter\View\View->render('control_internet', [], true)
 3 APPPATH\Controllers\ISP\ISPController.php(36): view('control_internet', [...])
 4 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISP\ISPController->index()
 5 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISP\ISPController))
 6 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-13 12:39:20 --> Invalid file: control_internet.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('control_internet.php')
 2 SYSTEMPATH\Common.php(1135): CodeIgniter\View\View->render('control_internet', [], true)
 3 APPPATH\Controllers\ISP\ISPController.php(36): view('control_internet', [...])
 4 SYSTEMPATH\CodeIgniter.php(925): App\Controllers\ISP\ISPController->index()
 5 SYSTEMPATH\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ISP\ISPController))
 6 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
